version: '2.4'

services:
  elasticsearch:
    image: elasticsearch:8.13.0
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
      - 9300

  test:
    image: elasticsearch:8.13.0
    volumes:
      - ./test-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    expose:
      - 9200
      - 9300
